name: build-test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Merge Conflict finder
        uses: olivernybroe/action-conflict-finder@v4.0

      - name: Install Dependencies
        run: npm install

      - name: Run ESLint on express-server package
        run: npm run lint:express-server

      - name: Run ESLint on web-react package
        run: npm run lint:web-react

      - name: Generate Prisma
        run: npm run prisma:generate

      - name: Build app
        run: npm run build --if-present

      - name: Run tests
        run: npm test
