name: build-test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]


jobs:
  build:
    name: build-test
    env:
      ACCESS_TOKEN_SECRET: '${{ secrets.ACCESS_TOKEN_SECRET }}'
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }} and Cache
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: |
            packages/express-server/package-lock.json
            packages/web-react/package-lock.json
          
      - name: Merge Conflict finder
        uses: olivernybroe/action-conflict-finder@v4.0

      - name: Install Dependencies & Bootstrap
        run: |
              npm ci
              npx lerna bootstrap

      - name: Format express-server package
        run: npm run format:express-server

      - name: Format web-react package
        run: npm run format:web-react

      - name: Run ESLint on express-server package
        run: npm run lint:express-server

      - name: Run ESLint on web-react package
        run: npm run lint:web-react

      - name: Generate Schema
        run: npm run generate

      - name: Build app
        run: npm run build --if-present

      - name: Run tests
        run: npm test
